#!/bin/sh

# 中文本地化
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en_US

# 让这些文件不要污染主目录
USERXSESSION=$XDG_CACHE_HOME/X11/xsession
USERXSESSIONRC=$XDG_CACHE_HOME/X11/xsessionrc
ALTUSERXSESSION=$XDG_CACHE_HOME/X11/Xsession
ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors

# 不能删除这个if块
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


/usr/bin/prime-offload
xmodmap $XDG_CONFIG_HOME/X11/xmodmap
exec awesome