#!/bin/sh

export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US

USERXSESSION=$XDG_CACHE_HOME/X11/xsession
USERXSESSIONRC=$XDG_CACHE_HOME/X11/xsessionrc
ALTUSERXSESSION=$XDG_CACHE_HOME/X11/Xsession
ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors

userresources=$XDG_CONFIG_HOME/X11/Xresources
sysresources=/etc/X11/xinit/.Xresources

export PATH=$XDG_CONFIG_HOME/rofi/rofi-translate:$PATH

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# 不起作用
# usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
# sysmodmap=/etc/X11/xinit/.Xmodmap
# if [ -f $sysmodmap ]; then
#     xmodmap $sysmodmap
# fi
# if [ -f "$usermodmap" ]; then
#     xmodmap "$usermodmap"
# fi

# xcape -e 'Mode_switch=Escape' &

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec awesome
